### ISSUE TITLE
Question on monetary unit (US$2010 vs. 2017 vs. 2020)

### ISSUE THREAD

**Issue by orichters** [orichters/common-definitions#2]
NAVIGATE used 2010, but maybe it is time to move to something like US$2020?

Edit: The SSP update uses US$2017, so that would be my preference.

**Comment by FlorianLeblancDr** [comment]
@IAMconsortium/common-definitions-macro-economy
@lolow @raymondmi
(Please tag for every issue (so that the four of us can receive notifications).

This issue has been raised by Daniel for everyone here
https://github.com/IAMconsortium/common-definitions/pull/54#issue-2132658784

I suggested to stick to $2010 (this will move over projects).

**Comment by danielhuppmann** [comment]
For your information, the **iam-units** package already supports currency-deflation for USD, see [here](https://github.com/IAMconsortium/units/blob/e22eab633e1aa65ac89ab110644396fab10aa77f/iam_units/data/definitions.txt#L63).

In pyam, it's as easy as 
```python
df.convert_unit("USD_2010", "USD_2020")
```
The **iam-units** package can also be used directly as a **pint.UnitRegistry** (read the docs at https://pint.readthedocs.io).

**Comment by lolow** [comment]
I agree to stick to $2010, but in a more general way, the monetary unit should be defined at database level, $2010 being the default. 
Some thoughts:
- A long placeholder could be "measure of monetary flow per unit of time". 
- Accepted values could be those defined in the `iam-units` package, following @danielhuppmann's comment. 
- This way, euro or national currency for specific database would be compatible if available in the package.

**Comment by FlorianLeblancDr** [comment]
This is good suggestions Laurent.
May be you can open an issue on this for everyone?

I am sure Shinichiro will appreciate as the template is also supposed to be used for national databases, included the current call for national scenarios he is working on.
